SELECT 
    FP.PASTA,
    -- Andamentos específicos

    anda_TERCEIRIZACAO_MIGRACAO.TIPO_ANDAMENTO AS AND_TERCEIRIZACAO_MIGRACAO,
    anda_TERCEIRIZACAO_MIGRACAO.DATA_ANDAMENTO AS DATA_AND_TERCEIRIZACAO_MIGRACAO,

    anda_ACAO_NAO_AJUIZADA.TIPO_ANDAMENTO AS ACAO_NAO_AJUIZADA,
    anda_ACAO_NAO_AJUIZADA.DATA_ANDAMENTO AS DATA_ACAO_NAO_AJUIZADA,
    
    anda_DOCUMENTACAO_APTA_AO_AJUIZAMENTO.TIPO_ANDAMENTO AS DOCUMENTACAO_APTA_AO_AJUIZAMENTO,
    anda_DOCUMENTACAO_APTA_AO_AJUIZAMENTO.DATA_ANDAMENTO AS DATA_DOCUMENTACAO_APTA_AO_AJUIZAMENTO,
    
    anda_CONTRATO_COM_GARANTIA.TIPO_ANDAMENTO AS CONTRATO_COM_GARANTIA,
    anda_CONTRATO_COM_GARANTIA.DATA_ANDAMENTO AS DATA_CONTRATO_COM_GARANTIA,
    
    anda_SOLICITACAO_DE_ORIENTACAO_JURIDICA.TIPO_ANDAMENTO AS SOLICITACAO_DE_ORIENTACAO_JURIDICA,
    anda_SOLICITACAO_DE_ORIENTACAO_JURIDICA.DATA_ANDAMENTO AS DATA_SOLICITACAO_DE_ORIENTACAO_JURIDICA,
    
    anda_ORIENTACAO_JURIDICA_DADA.TIPO_ANDAMENTO AS ORIENTACAO_JURIDICA_DADA,
    anda_ORIENTACAO_JURIDICA_DADA.DATA_ANDAMENTO AS DATA_ORIENTACAO_JURIDICA_DADA,
    
    anda_ENDERECO_VALIDADO.TIPO_ANDAMENTO AS ENDERECO_VALIDADO,
    anda_ENDERECO_VALIDADO.DATA_ANDAMENTO AS DATA_ENDERECO_VALIDADO,
    
    anda_ENDERECO_NAO_VALIDADO.TIPO_ANDAMENTO AS ENDERECO_NAO_VALIDADO,
    anda_ENDERECO_NAO_VALIDADO.DATA_ANDAMENTO AS DATA_ENDERECO_NAO_VALIDADO,
    
    anda_SOLICITACAO_DE_GUIAS.TIPO_ANDAMENTO AS SOLICITACAO_DE_GUIAS,
    anda_SOLICITACAO_DE_GUIAS.DATA_ANDAMENTO AS DATA_SOLICITACAO_DE_GUIAS,
    
    anda_INICIAL_CONFECCIONADA.TIPO_ANDAMENTO AS INICIAL_CONFECCIONADA,
    anda_INICIAL_CONFECCIONADA.DATA_ANDAMENTO AS DATA_INICIAL_CONFECCIONADA,
    
    anda_INICIAL_ENCAMINHADA_PARA_DISTRIBUICAO.TIPO_ANDAMENTO AS INICIAL_ENCAMINHADA_PARA_DISTRIBUICAO,
    anda_INICIAL_ENCAMINHADA_PARA_DISTRIBUICAO.DATA_ANDAMENTO AS DATA_INICIAL_ENCAMINHADA_PARA_DISTRIBUICAO,
    
    anda_INICIAL_PROTOCOLADA.TIPO_ANDAMENTO AS INICIAL_PROTOCOLADA,
    anda_INICIAL_PROTOCOLADA.DATA_ANDAMENTO AS DATA_INICIAL_PROTOCOLADA,
    
    anda_AJUIZAMENTO_SUSPENSO.TIPO_ANDAMENTO AS AJUIZAMENTO_SUSPENSO,
    anda_AJUIZAMENTO_SUSPENSO.DATA_ANDAMENTO AS DATA_AJUIZAMENTO_SUSPENSO,
    
    anda_AJUIZAMENTO_RETOMADO.TIPO_ANDAMENTO AS AJUIZAMENTO_RETOMADO,
    anda_AJUIZAMENTO_RETOMADO.DATA_ANDAMENTO AS DATA_AJUIZAMENTO_RETOMADO,
    
    anda_REVOGACAO_DA_CONTRATACAO.TIPO_ANDAMENTO AS REVOGACAO_DA_CONTRATACAO,
    anda_REVOGACAO_DA_CONTRATACAO.DATA_ANDAMENTO AS DATA_REVOGACAO_DA_CONTRATACAO,
    
    anda_RELATORIO_DE_REAJUIZAMENTO.TIPO_ANDAMENTO AS RELATORIO_DE_REAJUIZAMENTO,
    anda_RELATORIO_DE_REAJUIZAMENTO.DATA_ANDAMENTO AS DATA_RELATORIO_DE_REAJUIZAMENTO,
    
    anda_PETICAO_DE_DESISTENCIA.TIPO_ANDAMENTO AS PETICAO_DE_DESISTENCIA,
    anda_PETICAO_DE_DESISTENCIA.DATA_ANDAMENTO AS DATA_PETICAO_DE_DESISTENCIA,
    
    anda_PASTA_REABERTA.TIPO_ANDAMENTO AS PASTA_REABERTA,
    anda_PASTA_REABERTA.DATA_ANDAMENTO AS DATA_PASTA_REABERTA,
    
    anda_RECOLHER_CUSTAS_INICIAIS_DA_ACAO.TIPO_ANDAMENTO AS RECOLHER_CUSTAS_INICIAIS_DA_ACAO,
    anda_RECOLHER_CUSTAS_INICIAIS_DA_ACAO.DATA_ANDAMENTO AS DATA_RECOLHER_CUSTAS_INICIAIS_DA_ACAO,
    
    anda_CORRIGIR_RECOLHIMENTO_DE_GUIAS.TIPO_ANDAMENTO AS CORRIGIR_RECOLHIMENTO_DE_GUIAS,
    anda_CORRIGIR_RECOLHIMENTO_DE_GUIAS.DATA_ANDAMENTO AS DATA_CORRIGIR_RECOLHIMENTO_DE_GUIAS,
    
    anda_SOLICITADO_MATRICULA_ARISP.TIPO_ANDAMENTO AS SOLICITADO_MATRICULA_ARISP,
    anda_SOLICITADO_MATRICULA_ARISP.DATA_ANDAMENTO AS DATA_SOLICITADO_MATRICULA_ARISP,
    
    anda_INDICACAO_DE_BENS_PENHORA_BB.TIPO_ANDAMENTO AS INDICACAO_DE_BENS_PENHORA_BB,
    anda_INDICACAO_DE_BENS_PENHORA_BB.DATA_ANDAMENTO AS DATA_INDICACAO_DE_BENS_PENHORA_BB,
    
    anda_ANALISE_DE_MATRICULA_NEGATIVA.TIPO_ANDAMENTO AS ANALISE_DE_MATRICULA_NEGATIVA,
    anda_ANALISE_DE_MATRICULA_NEGATIVA.DATA_ANDAMENTO AS DATA_ANALISE_DE_MATRICULA_NEGATIVA,
    
    anda_PESQUISA_ARISP.TIPO_ANDAMENTO AS PESQUISA_ARISP,
    anda_PESQUISA_ARISP.DATA_ANDAMENTO AS DATA_PESQUISA_ARISP,
    
    anda_AJUIZAMENTO.TIPO_ANDAMENTO AS AJUIZAMENTO,
    anda_AJUIZAMENTO.DATA_ANDAMENTO AS DATA_AJUIZAMENTO,

    -- Compromissos específicos
    comp_CUSTAS.TIPO_COMPROMISSO AS TIPO_COMPROMISSO_CUSTAS,
    comp_CUSTAS.STATUS_COMPROMISSO AS STATUS_COMPROMISSO_CUSTAS,
    
    comp_RECOLHER_CUSTAS_INICIAIS_DA_ACAO.TIPO_COMPROMISSO AS TIPO_COMPROMISSO_RECOLHER_CUSTAS,
    comp_RECOLHER_CUSTAS_INICIAIS_DA_ACAO.STATUS_COMPROMISSO AS STATUS_COMPROMISSO_RECOLHER_CUSTAS,
    
    comp_RECOLHER_TAXA_DE_DISTRIBUICAO_DOS_AUTOS.TIPO_COMPROMISSO AS TIPO_COMPROMISSO_RECOLHER_TAXA,
    comp_RECOLHER_TAXA_DE_DISTRIBUICAO_DOS_AUTOS.STATUS_COMPROMISSO AS STATUS_COMPROMISSO_RECOLHER_TAXA,
    
    comp_CORRIGIR_RECOLHIMENTO_DE_GUIAS.TIPO_COMPROMISSO AS TIPO_COMPROMISSO_CORRIGIR_GUIAS,
    comp_CORRIGIR_RECOLHIMENTO_DE_GUIAS.STATUS_COMPROMISSO AS STATUS_COMPROMISSO_CORRIGIR_GUIAS,

    comp_VALIDAR_PETICAO.TIPO_COMPROMISSO AS TIPO_COMPROMISSO_VALIDAR_PETICAO,
    comp_VALIDAR_PETICAO.STATUS_COMPROMISSO AS STATUS_COMPROMISSO_VALIDAR_PETICAO,

    -- Documentos específicos
    doc_DOC_INICIAL.TIPO_DOCUMENTO AS DOC_INICIAL,
    doc_DOC_INICIAL.CADASTRADO_EM_DOCUMENTO AS DATA_CADASTRO_DOC_INICIAL,

    doc_DOCUMENTACAO_APTA_AO_AJUIZAMENTO.TIPO_DOCUMENTO AS DOCUMENTACAO_APTA_AO_AJUIZAMENTO,
    doc_DOCUMENTACAO_APTA_AO_AJUIZAMENTO.CADASTRADO_EM_DOCUMENTO AS DATA_CADASTRO_DOCUMENTACAO_APTA_AO_AJUIZAMENTO,   

    doc_DOCUMENTOS_QUE_INSTRUEM_A_INICIAL.TIPO_DOCUMENTO AS DOCUMENTOS_QUE_INSTRUEM_A_INICIAL,
    doc_DOCUMENTOS_QUE_INSTRUEM_A_INICIAL.CADASTRADO_EM_DOCUMENTO AS DATA_CADASTRO_DOCUMENTOS_QUE_INSTRUEM_A_INICIAL 

FROM Juridico.FichaProcessual FP WITH(NOLOCK)

-- Andamento "TERCEIRIZACAO/MIGRACAO"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'TERCEIRIZAÇÃO/MIGRAÇÃO'
) anda_TERCEIRIZACAO_MIGRACAO
ON FP.PASTA = anda_TERCEIRIZACAO_MIGRACAO.PASTA AND anda_TERCEIRIZACAO_MIGRACAO.rn = 1

-- Andamento "ACAO NAO AJUIZADA"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'ACAO NAO AJUIZADA'
) anda_ACAO_NAO_AJUIZADA
ON FP.PASTA = anda_ACAO_NAO_AJUIZADA.PASTA AND anda_ACAO_NAO_AJUIZADA.rn = 1

-- Andamento "DOCUMENTAÇÃO APTA AO AJUIZAMENTO - BB"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'DOCUMENTAÇÃO APTA AO AJUIZAMENTO - BB'
) anda_DOCUMENTACAO_APTA_AO_AJUIZAMENTO
ON FP.PASTA = anda_DOCUMENTACAO_APTA_AO_AJUIZAMENTO.PASTA AND anda_DOCUMENTACAO_APTA_AO_AJUIZAMENTO.rn = 1

-- Andamento "Contrato COM GARANTIA"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO IN(
        'CONTRATO COM GARANTIA / BEM IMÓVEL',
        'CONTRATO COM GARANTIA / BEM MÓVEL',
        'CONTRATO COM GARANTIA / BENS DIVERSOS')
) anda_CONTRATO_COM_GARANTIA
ON FP.PASTA = anda_CONTRATO_COM_GARANTIA.PASTA AND anda_CONTRATO_COM_GARANTIA.rn = 1

-- Andamento "SOLICITAÇÃO DE ORIENTAÇÃO JURÍDICA"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'SOLICITAÇÃO DE ORIENTAÇÃO JURÍDICA'
) anda_SOLICITACAO_DE_ORIENTACAO_JURIDICA
ON FP.PASTA = anda_SOLICITACAO_DE_ORIENTACAO_JURIDICA.PASTA AND anda_SOLICITACAO_DE_ORIENTACAO_JURIDICA.rn = 1

-- Andamento "ORIENTAÇÃO JURÍDICA DADA"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'ORIENTAÇÃO JURÍDICA DADA'
) anda_ORIENTACAO_JURIDICA_DADA
ON FP.PASTA = anda_ORIENTACAO_JURIDICA_DADA.PASTA AND anda_ORIENTACAO_JURIDICA_DADA.rn = 1

-- Andamento "ENDEREÇO VALIDADO"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'ENDEREÇO VALIDADO'
) anda_ENDERECO_VALIDADO
ON FP.PASTA = anda_ENDERECO_VALIDADO.PASTA AND anda_ENDERECO_VALIDADO.rn = 1

-- Andamento "ENDEREÇO NÃO VALIDADO"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'ENDEREÇO NÃO VALIDADO'
) anda_ENDERECO_NAO_VALIDADO
ON FP.PASTA = anda_ENDERECO_NAO_VALIDADO.PASTA AND anda_ENDERECO_NAO_VALIDADO.rn = 1

-- Andamento "SOLICITAÇÃO DE GUIAS"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'SOLICITAÇÃO DE GUIAS'
) anda_SOLICITACAO_DE_GUIAS
ON FP.PASTA = anda_SOLICITACAO_DE_GUIAS.PASTA AND anda_SOLICITACAO_DE_GUIAS.rn = 1

-- Andamento "INICIAL CONFECCIONADA"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'INICIAL CONFECCIONADA'
) anda_INICIAL_CONFECCIONADA
ON FP.PASTA = anda_INICIAL_CONFECCIONADA.PASTA AND anda_INICIAL_CONFECCIONADA.rn = 1

-- Andamento "INICIAL ENCAMINHADA PARA DISTRIBUIÇÃO"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'INICIAL ENCAMINHADA PARA DISTRIBUIÇÃO'
) anda_INICIAL_ENCAMINHADA_PARA_DISTRIBUICAO
ON FP.PASTA = anda_INICIAL_ENCAMINHADA_PARA_DISTRIBUICAO.PASTA AND anda_INICIAL_ENCAMINHADA_PARA_DISTRIBUICAO.rn = 1

-- Andamento "INICIAL PROTOCOLADA"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'INICIAL PROTOCOLADA'
) anda_INICIAL_PROTOCOLADA
ON FP.PASTA = anda_INICIAL_PROTOCOLADA.PASTA AND anda_INICIAL_PROTOCOLADA.rn = 1

-- Andamento "AJUIZAMENTO SUSPENSO"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'AJUIZAMENTO SUSPENSO'
) anda_AJUIZAMENTO_SUSPENSO
ON FP.PASTA = anda_AJUIZAMENTO_SUSPENSO.PASTA AND anda_AJUIZAMENTO_SUSPENSO.rn = 1

-- Andamento "AJUIZAMENTO RETOMADO"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'AJUIZAMENTO RETOMADO'
) anda_AJUIZAMENTO_RETOMADO
ON FP.PASTA = anda_AJUIZAMENTO_RETOMADO.PASTA AND anda_AJUIZAMENTO_RETOMADO.rn = 1

-- Andamento "REVOGAÇÃO DA CONTRATAÇÃO"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'REVOGAÇÃO DA CONTRATAÇÃO'
) anda_REVOGACAO_DA_CONTRATACAO
ON FP.PASTA = anda_REVOGACAO_DA_CONTRATACAO.PASTA AND anda_REVOGACAO_DA_CONTRATACAO.rn = 1

-- Andamento "RELATÓRIO DE REAJUIZAMENTO"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'RELATÓRIO DE REAJUIZAMENTO'
) anda_RELATORIO_DE_REAJUIZAMENTO
ON FP.PASTA = anda_RELATORIO_DE_REAJUIZAMENTO.PASTA AND anda_RELATORIO_DE_REAJUIZAMENTO.rn = 1

-- Andamento "PETIÇÃO DE DESISTÊNCIA"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'PETIÇÃO DE DESISTÊNCIA'
) anda_PETICAO_DE_DESISTENCIA
ON FP.PASTA = anda_PETICAO_DE_DESISTENCIA.PASTA AND anda_PETICAO_DE_DESISTENCIA.rn = 1

-- Andamento "PASTA REABERTA"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'PASTA REABERTA'
) anda_PASTA_REABERTA
ON FP.PASTA = anda_PASTA_REABERTA.PASTA AND anda_PASTA_REABERTA.rn = 1

-- Andamento "RECOLHER CUSTAS INICIAIS DA AÇÃO"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'RECOLHER CUSTAS INICIAIS DA AÇÃO'
) anda_RECOLHER_CUSTAS_INICIAIS_DA_ACAO
ON FP.PASTA = anda_RECOLHER_CUSTAS_INICIAIS_DA_ACAO.PASTA AND anda_RECOLHER_CUSTAS_INICIAIS_DA_ACAO.rn = 1

-- Andamento "CORRIGIR RECOLHIMENTO DE GUIAS"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'CORRIGIR RECOLHIMENTO DE GUIAS'
) anda_CORRIGIR_RECOLHIMENTO_DE_GUIAS
ON FP.PASTA = anda_CORRIGIR_RECOLHIMENTO_DE_GUIAS.PASTA AND anda_CORRIGIR_RECOLHIMENTO_DE_GUIAS.rn = 1

-- Andamento "SOLICITADO MATRICULA ARISP"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'SOLICITADO MATRICULA ARISP'
) anda_SOLICITADO_MATRICULA_ARISP
ON FP.PASTA = anda_SOLICITADO_MATRICULA_ARISP.PASTA AND anda_SOLICITADO_MATRICULA_ARISP.rn = 1

-- Andamento "INDICAÇÃO DE BENS - PENHORA BB"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'INDICAÇÃO DE BENS - PENHORA BB'
) anda_INDICACAO_DE_BENS_PENHORA_BB
ON FP.PASTA = anda_INDICACAO_DE_BENS_PENHORA_BB.PASTA AND anda_INDICACAO_DE_BENS_PENHORA_BB.rn = 1

-- Andamento "ANALISE DE MATRICULA NEGATIVA"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'ANALISE DE MATRICULA NEGATIVA'
) anda_ANALISE_DE_MATRICULA_NEGATIVA
ON FP.PASTA = anda_ANALISE_DE_MATRICULA_NEGATIVA.PASTA AND anda_ANALISE_DE_MATRICULA_NEGATIVA.rn = 1

-- Andamento de PESQUISA ARISP
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO IN (
        'RESULTADO PESQUISA ESPECIFICA ARISP – POSITIVO',
        'RESULTADO PESQUISA ESPECIFICA ARISP - NEGATIVA'
        )
) anda_PESQUISA_ARISP
ON FP.PASTA = anda_PESQUISA_ARISP.PASTA AND anda_PESQUISA_ARISP.rn = 1

-- Andamento "AJUIZAMENTO"
LEFT JOIN (
    SELECT PASTA, TIPO_ANDAMENTO, DATA_ANDAMENTO, ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_ANDAMENTO DESC, HORA_ANDAMENTO DESC) AS rn
    FROM Juridico.Andamentos
    WHERE TIPO_ANDAMENTO = 'AJUIZAMENTO'
) anda_AJUIZAMENTO
ON FP.PASTA = anda_AJUIZAMENTO.PASTA AND anda_AJUIZAMENTO.rn = 1

-- Compromisso "VALIDAR PETIÇÃO"
LEFT JOIN (
    SELECT PASTA, TIPO_COMPROMISSO,STATUS_COMPROMISSO, DATA_LIMITE_COMPROMISSO,DATA_CADASTRO_COMPROMISO,
    ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_LIMITE_COMPROMISSO DESC) AS rn
    FROM Juridico.Compromissos
    WHERE TIPO_COMPROMISSO = 'VALIDAR PETIÇÃO INICIAL'
) comp_VALIDAR_PETICAO
ON FP.PASTA = comp_VALIDAR_PETICAO.PASTA AND comp_VALIDAR_PETICAO.rn = 1

-- Compromissos de "CUSTAS"
LEFT JOIN (
    SELECT PASTA, TIPO_COMPROMISSO,STATUS_COMPROMISSO, DATA_LIMITE_COMPROMISSO,DATA_CADASTRO_COMPROMISO,
    ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_LIMITE_COMPROMISSO DESC) AS rn
    FROM Juridico.Compromissos
    WHERE TIPO_COMPROMISSO IN(
        'RECOLHER CUSTAS INICIAIS DA AÇÃO',
        'RECOLHER TAXA DE DISTRIBUIÇÃO DOS AUTOS' ,
        'CORRIGIR RECOLHIMENTO DE GUIAS')
) comp_CUSTAS
ON FP.PASTA = comp_CUSTAS.PASTA AND comp_CUSTAS.rn = 1

-- Compromisso "RECOLHER CUSTAS INICIAIS DA AÇÃO"
LEFT JOIN (
    SELECT PASTA, TIPO_COMPROMISSO,STATUS_COMPROMISSO, DATA_LIMITE_COMPROMISSO,DATA_CADASTRO_COMPROMISO,
    ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_LIMITE_COMPROMISSO DESC) AS rn
    FROM Juridico.Compromissos
    WHERE TIPO_COMPROMISSO = 'RECOLHER CUSTAS INICIAIS DA AÇÃO'
) comp_RECOLHER_CUSTAS_INICIAIS_DA_ACAO
ON FP.PASTA = comp_RECOLHER_CUSTAS_INICIAIS_DA_ACAO.PASTA AND comp_RECOLHER_CUSTAS_INICIAIS_DA_ACAO.rn = 1

-- Compromisso "RECOLHER TAXA DE DISTRIBUIÇÃO DOS AUTOS"
LEFT JOIN (
    SELECT PASTA, TIPO_COMPROMISSO,STATUS_COMPROMISSO, DATA_LIMITE_COMPROMISSO,DATA_CADASTRO_COMPROMISO,
    ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_LIMITE_COMPROMISSO DESC) AS rn
    FROM Juridico.Compromissos
    WHERE TIPO_COMPROMISSO = 'RECOLHER TAXA DE DISTRIBUIÇÃO DE AUTOS'
) comp_RECOLHER_TAXA_DE_DISTRIBUICAO_DOS_AUTOS
ON FP.PASTA = comp_RECOLHER_TAXA_DE_DISTRIBUICAO_DOS_AUTOS.PASTA AND comp_RECOLHER_TAXA_DE_DISTRIBUICAO_DOS_AUTOS.rn = 1

-- Compromisso "CORRIGIR RECOLHIMENTO DE GUIAS"
LEFT JOIN (
    SELECT PASTA, TIPO_COMPROMISSO,STATUS_COMPROMISSO, DATA_LIMITE_COMPROMISSO,DATA_CADASTRO_COMPROMISO,
    ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY DATA_LIMITE_COMPROMISSO DESC) AS rn
    FROM Juridico.Compromissos
    WHERE TIPO_COMPROMISSO = 'CORRIGIR RECOLHIMENTO DE GUIA'
) comp_CORRIGIR_RECOLHIMENTO_DE_GUIAS
ON FP.PASTA = comp_CORRIGIR_RECOLHIMENTO_DE_GUIAS.PASTA AND comp_CORRIGIR_RECOLHIMENTO_DE_GUIAS.rn = 1

-- Documento "CORRIGIR RECOLHIMENTO DE GUIAS"
LEFT JOIN (
    SELECT PASTA, TIPO_DOCUMENTO,CADASTRADO_EM_DOCUMENTO,
    ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY CADASTRADO_EM_DOCUMENTO DESC) AS rn
    FROM Juridico.Documentos
    WHERE TIPO_DOCUMENTO = 'DOCUMENTOS QUE INSTRUEM A INICIAL'
) doc_DOCUMENTOS_QUE_INSTRUEM_A_INICIAL
ON FP.PASTA = doc_DOCUMENTOS_QUE_INSTRUEM_A_INICIAL.PASTA AND doc_DOCUMENTOS_QUE_INSTRUEM_A_INICIAL.rn = 1

-- Documento "DOCUMENTAÇÃO APTA AO AJUIZAMENTO - BB"
LEFT JOIN (
    SELECT PASTA, TIPO_DOCUMENTO,CADASTRADO_EM_DOCUMENTO,
    ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY CADASTRADO_EM_DOCUMENTO DESC) AS rn
    FROM Juridico.Documentos
    WHERE TIPO_DOCUMENTO = 'DOCUMENTAÇÃO APTA AO AJUIZAMENTO - BB'
) doc_DOCUMENTACAO_APTA_AO_AJUIZAMENTO
ON FP.PASTA = doc_DOCUMENTACAO_APTA_AO_AJUIZAMENTO.PASTA AND doc_DOCUMENTACAO_APTA_AO_AJUIZAMENTO.rn = 1

-- Documento "DOC. INICIAL"
LEFT JOIN (
    SELECT PASTA, TIPO_DOCUMENTO,CADASTRADO_EM_DOCUMENTO,
    ROW_NUMBER() OVER (PARTITION BY PASTA ORDER BY CADASTRADO_EM_DOCUMENTO DESC) AS rn
    FROM Juridico.Documentos
    WHERE TIPO_DOCUMENTO = 'DOC. INICIAL'
) doc_DOC_INICIAL
ON FP.PASTA = doc_DOC_INICIAL.PASTA AND doc_DOC_INICIAL.rn = 1

WHERE FP.PRODUTO IN (
    'BANCO DO BRASIL - COBRANÇA - SEGMENTO 1',
    'BANCO DO BRASIL - COBRANÇA - SEGMENTO 2',
    'BANCO DO BRASIL - COBRANÇA - SEGMENTO 3',
    'BB - COBRANÇA',
    'BANCO DO BRASIL - COBRANÇA - ATIPICAS')
AND FP.STATUS_PASTA = 'ATIVO'


