WITH CTE_FICHA AS (
    SELECT
    FP.PASTA,
    FP.STATUS_PASTA,
    FP.BJ,
    FP.NPJ_INCIDENTE,
    FP.PRODUTO,
    FP.CARTEIRA,
    FP.DATA_CADASTRO_PASTA,
    FP.DATA_TERCEIRIZACAO,
    FP.FASE

    FROM JURIDICO.FICHAPROCESSUAL FP WITH(NOLOCK)
    WHERE FP.PRODUTO = 'PAN'
)

    SELECT 

    FP.PASTA,
    FP.STATUS_PASTA,
    FP.BJ,
    FP.NPJ_INCIDENTE,
    FP.PRODUTO,
    FP.CARTEIRA,
    FP.DATA_CADASTRO_PASTA,
    FP.DATA_TERCEIRIZACAO,
    FP.FASE,
    
    --- VERIFICAÇÃO : TIVEMOS SENTENÇA ?
    CASE 
        WHEN SNT.RESULTADO_DA_ACAO_ANALISE_DECISAO IS NOT NULL
        THEN 'SIM'
        ELSE 'NAO'
        END AS [COM SENTENÇA?],
    
    SNT.RESULTADO_DA_ACAO_ANALISE_DECISAO AS RESULTADO_DA_SENTENCA,
    SNT.DATA_DECISAO_ANALISE_DECISAO AS DATA_SENTENCA,

    --- VERIFICAÇÃO : TIVERMOS RECURSO DE APELAÇÃO/INOMINADO?
    CASE
        WHEN PROTR.TIPO_DE_DOCUMENTO IS NOT NULL
        THEN 'SIM'
        ELSE 'NAO'
        END AS [COM RECURSO DE APELAÇÃO/INOMINADO?],
    
    PROTR.TIPO_DE_DOCUMENTO AS TIPO_RECURSO,
    PROTR.DATA_EXECUCAO_TAREFA AS DATA_PROTOCOLO_RECURSO,

    --- VERIFICAÇÃO : TIVEMOS CONTRARRAZÕES DE RECURSO DE APELAÇÃO/INOMINADO?
    CASE
        WHEN PROTC.TIPO_DE_DOCUMENTO IS NOT NULL
        THEN 'SIM'
        ELSE 'NAO'
        END AS [COM CONTRARRAZOES DE RECURSO DE APELACAO/INOMINADO],
    
    PROTC.TIPO_DE_DOCUMENTO AS TIPO_CONTRARRAZOES,
    PROTR.DATA_EXECUCAO_TAREFA AS DATA_PROTOCOLO_CONTRARRAZOES,

    --- VERIFICAÇÃO : TIVEMOS ACÓRDÃO COM ORIGEM DE RECURSO DE APELAÇÃO/INOMINADO?
    CASE
        WHEN ACOR.RESULTADO_DA_DECISAO_ANALISE_DECISAO IS NOT NULL
        THEN 'SIM'
        ELSE 'NAO'
        END AS [COM ACÓRDÃO(ORIGEM DE RECURSO DE APELACAO/INOMINADO)],
    
    ACOR.RESULTADO_DA_DECISAO_ANALISE_DECISAO AS TIPO_ACORDAO,
    ACOR.DATA_DECISAO_ANALISE_DECISAO AS DATA_ACORDAO,

    --- VERIFICAÇÃO : TIVEMOS PAGAMENTO? (TEDESCO)
    CASE 
        WHEN  PAGT.LIBERACAO_BANCO_PGTO_JUDICIAL IS NOT NULL
        THEN 'SIM'
        ELSE 'NAO'
        END AS [COM PAGAMENTO?],
    
    PAGT.LIBERACAO_BANCO_PGTO_JUDICIAL AS DATA_PAGAMENTO,
    PAGT.PAGAMENTO_EM_PGTO_JUDICIAL AS ORIGEM_PAGAMENTO,
    PAGT.VALOR_PAGO_PGTO_JUDICIAL AS VALOR_PAGAMENTO,

    --- VERIFICAÇÃO : ULTIMO COMPROMISSOS PENDENTE - PRAZO

    GP1.TIPO_PRAZO_GESTAO_PRAZO AS [1_PRAZO_PENDENTE],
    GP1.TIPO_COMPROMISSO_GESTAO_PRAZO AS [1_COMPROMISSO_PENDENTE],
    GP1.PRAZO_INTERNO_COMPROMISSO_GESTAO_PRAZO AS [1_DATA_LIMITE_PRAZO],

    GP2.TIPO_PRAZO_GESTAO_PRAZO AS [2_PRAZO_PENDENTE],
    GP2.TIPO_COMPROMISSO_GESTAO_PRAZO AS [2_COMPROMISSO_PENDENTE],
    GP2.PRAZO_INTERNO_COMPROMISSO_GESTAO_PRAZO AS [2_DATA_LIMITE_PRAZO],

    GP3.TIPO_PRAZO_GESTAO_PRAZO AS [3_PRAZO_PENDENTE],
    GP3.TIPO_COMPROMISSO_GESTAO_PRAZO AS [3_COMPROMISSO_PENDENTE],
    GP3.PRAZO_INTERNO_COMPROMISSO_GESTAO_PRAZO AS [3_DATA_LIMITE_PRAZO],

    --- VERIFICAÇÃO : ultimo prazo concluído;
    GPC.TIPO_PRAZO_GESTAO_PRAZO AS ULTIMO_PRAZO_CONCLUIDO,
    GPC.DATA_CONCLUSAO_PRAZO_GESTAO_PRAZO AS DATA_ULTIMO_PRAZO_CONCLUIDO,

    --- VERIFICAÇÃO : Ultimo andamento
    ANDAR.TIPO_ANDAMENTO AS TIPO_ULTIMO_ANDAMENTO,
    ANDAR.DATA_ANDAMENTO AS DATA_ULTIMO_ANDAMENTO,

    --- VERIFICACAO : Ultima publicação
    PUB.DATA_PUBLICACAO AS DATA_ULTIMA_PUBLICACAO,
    PUB.ANALISE_MOTIVO_CIENCIA_PUBLICACAO AS ANALISE_MOTIVO_CIENCIA_ULTIMA_PUBLICACAO,

    --- VERIFICAÇÃO : Esteira de Encerramento

    CASE 
        WHEN TRE.TAREFA IS NOT NULL
        THEN 'SIM'
        ELSE 'NAO'
        END AS [ESTA_NA_ESTEIRA_DE_ENCERRAMENTO?],

    TRE.TAREFA AS TAREFA_TRIARE_ENCERRAMENTO,
    TRE.STATUS_DO_ENCERRAMENTO_TRIARE,
    TRE.DATA_CRIACAO_TAREFA AS DATA_CRIACAO_TAREFA_ENCERRAMENTO

    FROM CTE_FICHA FP 

    --- 1º e 2º - se teve SENTENÇA (Módulo de análise de decisão) | Resultado da sentença (Módulo de análise de decisão)

LEFT JOIN (
    SELECT
        AD.PASTA,
        AD.TIPO_DE_DECISAO_ANALISE_DECISAO,
        AD.RESULTADO_DA_ACAO_ANALISE_DECISAO,
        AD.ORIGEM_DA_DECISAO_ANALISE_DECISAO,
        AD.DATA_DECISAO_ANALISE_DECISAO,
        ROW_NUMBER() OVER( PARTITION BY AD.PASTA ORDER BY AD.DATA_DECISAO_ANALISE_DECISAO DESC) AS RK
    FROM JURIDICO.ANALISE_DECISAO_RJ AD WITH(NOLOCK)
    WHERE AD.TIPO_DE_DECISAO_ANALISE_DECISAO = 'SENTENÇA'
    AND AD.RESULTADO_DA_DECISAO_ANALISE_DECISAO != 'SENTENÇA - 924  DO CPC'
    AND AD.RESULTADO_DA_DECISAO_ANALISE_DECISAO != 'EXTINÇÃO 924'
    AND AD.RESULTADO_DA_DECISAO_ANALISE_DECISAO != 'HOMOLOGAÇÃO DE ACORDO'
) SNT ON FP.PASTA = SNT.PASTA AND SNT.RK = 1

    --- 3º - se teve Recurso de apelação ou Recurso inominado (protocolo)

LEFT JOIN (
    SELECT
        PROT.PASTA,
        PROT.TIPO_DE_DOCUMENTO,
        PROT.DATA_EXECUCAO_TAREFA,
        ROW_NUMBER() OVER (PARTITION BY PROT.PASTA ORDER BY PROT.DATA_EXECUCAO_TAREFA DESC) AS RK
        FROM JURIDICO.TRIARE_PROTOCOLO PROT
        WHERE PROT.TAREFA = '18 - Anexar comprovante de protocolo'
        AND PROT.TIPO_DE_DOCUMENTO IN ('Recurso de Apelação (H)','Recurso Inominado')
) PROTR ON FP.PASTA = PROTR.PASTA AND PROTR.RK = 1

    --- 4º se teve Contrarrazões de Recurso de apelação ou Contrarrazões de Recurso inominado (Protocolo)

LEFT JOIN (
    SELECT
        PROT.PASTA,
        PROT.TIPO_DE_DOCUMENTO,
        PROT.DATA_EXECUCAO_TAREFA,
        ROW_NUMBER() OVER (PARTITION BY PROT.PASTA ORDER BY PROT.DATA_EXECUCAO_TAREFA DESC) AS RK
        FROM JURIDICO.TRIARE_PROTOCOLO PROT
        WHERE PROT.TAREFA = '18 - Anexar comprovante de protocolo'
        AND PROT.TIPO_DE_DOCUMENTO IN ('Contrarrazões de Recurso de Apelação (H)','Contrarrazões de Recurso Inominado')
) PROTC ON FP.PASTA = PROTC.PASTA AND PROTC.RK = 1

    --- 5º Se teve acórdão de origem de recurso de apelação e recurso inominado (Módulo de análise de decisão)

LEFT JOIN (
    SELECT
        AD.PASTA,
        AD.TIPO_DE_DECISAO_ANALISE_DECISAO,
        AD.RESULTADO_DA_ACAO_ANALISE_DECISAO,
        AD.RESULTADO_DA_DECISAO_ANALISE_DECISAO,
        AD.ORIGEM_DA_DECISAO_ANALISE_DECISAO,
        AD.DATA_DECISAO_ANALISE_DECISAO,
        ROW_NUMBER() OVER( PARTITION BY AD.PASTA ORDER BY AD.DATA_DECISAO_ANALISE_DECISAO DESC) AS RK
    FROM JURIDICO.ANALISE_DECISAO_RJ AD WITH(NOLOCK)
    WHERE AD.TIPO_DE_DECISAO_ANALISE_DECISAO = 'ACÓRDÃO'
    AND AD.ORIGEM_DA_DECISAO_ANALISE_DECISAO IN ('RECURSO DE APELAÇÃO','RECURSO INOMINADO')
) ACOR ON FP.PASTA = ACOR.PASTA AND ACOR.RK = 1

    --- 6º  Se teve pagamento (módulo de pagamento tedesco)

LEFT JOIN (
    SELECT 
        PAG.PASTA,
        PAG.LIBERACAO_BANCO_PGTO_JUDICIAL,
        PAG.STATUS_BEM_PGTO_JUDICIAL,
        PAG.PAGAMENTO_EM_PGTO_JUDICIAL,
        PAG.VALOR_PAGO_PGTO_JUDICIAL,
        ROW_NUMBER() OVER( PARTITION BY PAG.PASTA ORDER BY PAG.LIBERACAO_BANCO_PGTO_JUDICIAL DESC) AS RK
    FROM JURIDICO.PAGAMENTOS_JUDICIAIS_DEPOSITOS PAG WITH(NOLOCK)
    WHERE PAG.LIBERACAO_BANCO_PGTO_JUDICIAL IS NOT NULL
    AND PAG.STATUS_BEM_PGTO_JUDICIAL = 'PAGAMENTO LIBERADO'
    AND PAG.PAGAMENTO_EM_PGTO_JUDICIAL IN ('Garantia','Acordo','Condenação','Multa 538-cpc')
    ) PAGT ON FP.PASTA = PAGT.PASTA AND PAGT.RK = 1

    --- 7º Prazo mais antigo pendente = 1º

LEFT JOIN (
    SELECT
        GP.PASTA,
        GP.TIPO_PRAZO_GESTAO_PRAZO,
        GP.TIPO_COMPROMISSO_GESTAO_PRAZO,
        GP.PRAZO_INTERNO_GESTAO_PRAZO,
        GP.PRAZO_INTERNO_COMPROMISSO_GESTAO_PRAZO,
        ROW_NUMBER() OVER (
            PARTITION BY GP.PASTA 
            ORDER BY GP.PRAZO_INTERNO_COMPROMISSO_GESTAO_PRAZO ASC
        ) AS RK
    FROM JURIDICO.GESTAO_PRAZO GP WITH (NOLOCK)
    WHERE 
        GP.STATUS_PRAZO_GESTOA_PRAZO = 'PENDENTE'
        AND EXISTS (
            SELECT 1
            FROM JURIDICO.GESTAO_PRAZO GP2 WITH (NOLOCK)
            WHERE GP2.PASTA = GP.PASTA
              AND GP2.STATUS_COMPROMISSO_GESTAO_PRAZO = 'PENDENTE'
        )
) GP1 ON FP.PASTA = GP1.PASTA AND GP1.RK = 1

    
    --- 8º Prazo mais antigo pendente = 2º
LEFT JOIN (
    SELECT
        GP.PASTA,
        GP.TIPO_PRAZO_GESTAO_PRAZO,
        GP.TIPO_COMPROMISSO_GESTAO_PRAZO,
        GP.PRAZO_INTERNO_GESTAO_PRAZO,
        GP.PRAZO_INTERNO_COMPROMISSO_GESTAO_PRAZO,
        ROW_NUMBER() OVER (
            PARTITION BY GP.PASTA 
            ORDER BY GP.PRAZO_INTERNO_COMPROMISSO_GESTAO_PRAZO ASC
        ) AS RK
    FROM JURIDICO.GESTAO_PRAZO GP WITH (NOLOCK)
    WHERE 
        GP.STATUS_PRAZO_GESTOA_PRAZO = 'PENDENTE'
        AND EXISTS (
            SELECT 1
            FROM JURIDICO.GESTAO_PRAZO GP2 WITH (NOLOCK)
            WHERE GP2.PASTA = GP.PASTA
              AND GP2.STATUS_COMPROMISSO_GESTAO_PRAZO = 'PENDENTE'
        )
) GP2 ON FP.PASTA = GP2.PASTA AND GP2.RK = 2


    --- 9º Prazo mais antigo pendente = 3º
LEFT JOIN (
    SELECT
        GP.PASTA,
        GP.TIPO_PRAZO_GESTAO_PRAZO,
        GP.TIPO_COMPROMISSO_GESTAO_PRAZO,
        GP.PRAZO_INTERNO_GESTAO_PRAZO,
        GP.PRAZO_INTERNO_COMPROMISSO_GESTAO_PRAZO,
        ROW_NUMBER() OVER (
            PARTITION BY GP.PASTA 
            ORDER BY GP.PRAZO_INTERNO_COMPROMISSO_GESTAO_PRAZO ASC
        ) AS RK
    FROM JURIDICO.GESTAO_PRAZO GP WITH (NOLOCK)
    WHERE 
        GP.STATUS_PRAZO_GESTOA_PRAZO = 'PENDENTE'
        AND EXISTS (
            SELECT 1
            FROM JURIDICO.GESTAO_PRAZO GP2 WITH (NOLOCK)
            WHERE GP2.PASTA = GP.PASTA
              AND GP2.STATUS_COMPROMISSO_GESTAO_PRAZO = 'PENDENTE'
        )
) GP3 ON FP.PASTA = GP3.PASTA AND GP3.RK = 3
    
    
    --- 10º Ultimo prazo concluido
LEFT JOIN (
    SELECT
        GP.PASTA,
        GP.TIPO_PRAZO_GESTAO_PRAZO,
        GP.TIPO_COMPROMISSO_GESTAO_PRAZO,
        GP.DATA_CONCLUSAO_PRAZO_GESTAO_PRAZO,
        ROW_NUMBER() OVER( PARTITION BY GP.PASTA ORDER BY GP.DATA_CONCLUSAO_PRAZO_GESTAO_PRAZO DESC) AS RK
    FROM JURIDICO.GESTAO_PRAZO GP WITH (NOLOCK)
    WHERE GP.STATUS_PRAZO_GESTOA_PRAZO = 'Concluído'
    ) GPC ON FP.PASTA = GPC.PASTA AND GPC.RK = 1 

    --- 11º Ultimo andamento
LEFT JOIN (
    SELECT
    ANDA.PASTA,
    ANDA.TIPO_ANDAMENTO,
    ANDA.DATA_ANDAMENTO,
    ROW_NUMBER() OVER( PARTITION BY ANDA.PASTA ORDER BY ANDA.DATA_ANDAMENTO DESC) AS RK
    FROM JURIDICO.ANDAMENTOS ANDA WITH(NOLOCK)
) ANDAR ON FP.PASTA = ANDAR.PASTA AND ANDAR.RK = 1

    --- 12º Ultima Publicação
LEFT JOIN (
    SELECT
    PUB.PASTA,
    PUB.DATA_PUBLICACAO,
    PUB.ANALISE_MOTIVO_CIENCIA_PUBLICACAO,
    ROW_NUMBER() OVER(PARTITION BY PUB.PASTA ORDER BY PUB.DATA_PUBLICACAO DESC) AS RK
    FROM JURIDICO.PUBLICACOES PUB WITH(NOLOCK)
) PUB ON FP.PASTA = PUB.PASTA AND PUB.RK = 1

    --- 13º  se está base de encerramento e em algum submotivo
LEFT JOIN (
    SELECT
    TRE.PASTA,
    TRE.TAREFA,
    TRE.STATUS_DO_ENCERRAMENTO_TRIARE,
    TRE.DATA_CRIACAO_TAREFA,
    ROW_NUMBER() OVER(PARTITION BY TRE.PASTA ORDER BY TRE.DATA_CRIACAO_TAREFA DESC) AS RK
    FROM JURIDICO.TRIARE_ENCERRAMENTO TRE WITH(NOLOCK)
) TRE ON FP.PASTA = TRE.PASTA AND TRE.RK = 1




